### ISSUE TITLE
about the model ouput channel?

### ISSUE THREAD

**Issue by zz10001** [ChoiDM/LiTS#1]
Hi,
Thanks for your awesomework, I notice that your network output channel is 1 in train.ipynb, Is it have some problem when compute dice? 
![image](https://user-images.githubusercontent.com/39954774/68214311-25b42700-0018-11ea-9313-4e5308787571.png), It the sum of 0 and 1, not compute 0 and 1 Seperately .

**Comment by ChoiDM** [comment]
Thank you for your question.

The output channel doesn’t effect to computing dice score because before
the value is calculated, the tensor is flattened.

I hope my answer was helpful.
Thank you.

2019년 11월 5일 (화) 오후 11:43, zz10001 <notifications@github.com>님이 작성:

**Comment by zz10001** [comment]
Thakns for your kind help!
