### ISSUE TITLE
How can I get "model_7"?

### ISSUE THREAD

**Issue by Jeonous** [ChoiDM/LiTS#2]
Hi. 
In Training.ipynb has code like this:

model = model.get_layer("model_7")

and I run the note on the colab and I got ValueError like this.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-28-19bdcc1ab277> in <module>()
----> 1 model = model.get_layer("model_7")

/usr/local/lib/python3.6/dist-packages/keras/engine/network.py in get_layer(self, name, index)
    362                 return layer
    363 
--> 364         raise ValueError('No such layer: ' + name)
    365 
    366     @property

ValueError: No such layer: model_7

I found "model_1" in the model.summary(). but

model = model.get_layer("model_1")

didn't work.

I also looked for the get_layer () function, but couldn't solve it.

I need help...
Thanks for reading.

**Comment by ChoiDM** [comment]
Do you mind if I ask you upload the result image of model.summary()?


Thank you.

**Comment by Jeonous** [comment]
Thanks for answering, Choi.

I think I can't upload the image on this page.

here is the result of the model.summary() that I tried.


Model: "model_1"
### Layer (type)                    Output Shape         Param #     Connected to 
      
input (InputLayer)              (None, 64, 64, 1)    0                                            

conv1_1 (Conv2D)                (None, 64, 64, 32)   320         input[0][0]                      

conv1_1_bn (BatchNormalization) (None, 64, 64, 32)   128         conv1_1[0][0]                    

conv1_2 (Conv2D)                (None, 64, 64, 32)   9248        conv1_1_bn[0][0]                 

conv1_2_bn (BatchNormalization) (None, 64, 64, 32)   128         conv1_2[0][0]                    

pool1 (MaxPooling2D)            (None, 32, 32, 32)   0           conv1_2_bn[0][0]                 

conv2_1 (Conv2D)                (None, 32, 32, 64)   18496       pool1[0][0]                      

conv2_1_bn (BatchNormalization) (None, 32, 32, 64)   256         conv2_1[0][0]                    

conv2_2 (Conv2D)                (None, 32, 32, 64)   36928       conv2_1_bn[0][0]                 

conv2_2_bn (BatchNormalization) (None, 32, 32, 64)   256         conv2_2[0][0]                    

pool2 (MaxPooling2D)            (None, 16, 16, 64)   0           conv2_2_bn[0][0]                 

conv3_1 (Conv2D)                (None, 16, 16, 128)  73856       pool2[0][0]       
               
conv3_1_bn (BatchNormalization) (None, 16, 16, 128)  512         conv3_1[0][0]  
                  
conv3_2 (Conv2D)                (None, 16, 16, 128)  147584      conv3_1_bn[0][0]                 

conv3_2_bn (BatchNormalization) (None, 16, 16, 128)  512         conv3_2[0][0]                    

pool3 (MaxPooling2D)            (None, 8, 8, 128)    0           conv3_2_bn[0][0]                 

conv4_1 (Conv2D)                (None, 8, 8, 256)    295168      pool3[0][0]                      

conv4_1_bn (BatchNormalization) (None, 8, 8, 256)    1024        conv4_1[0][0]                    

conv4_2 (Conv2D)                (None, 8, 8, 256)    590080      conv4_1_bn[0][0]                 

conv4_2_bn (BatchNormalization) (None, 8, 8, 256)    1024        conv4_2[0][0]                    

pool4 (MaxPooling2D)            (None, 4, 4, 256)    0           conv4_2_bn[0][0]                 

conv5_1 (Conv2D)                (None, 4, 4, 512)    1180160     pool4[0][0]                      

conv5_1_bn (BatchNormalization) (None, 4, 4, 512)    2048        conv5_1[0][0]                    

conv5_2 (Conv2D)                (None, 4, 4, 512)    2359808     conv5_1_bn[0][0]                 

conv5_2_bn (BatchNormalization) (None, 4, 4, 512)    2048        conv5_2[0][0]                    

conv2d_transpose_1 (Conv2DTrans (None, 8, 8, 256)    524544      conv5_2_bn[0][0]                 

dropout_5 (Dropout)             (None, 8, 8, 256)    0           conv2d_transpose_1[0][0]         

concat6 (Concatenate)           (None, 8, 8, 512)    0           conv4_2_bn[0][0]                 
                                                                 dropout_5[0][0]                  

conv6_1 (Conv2D)                (None, 8, 8, 256)    1179904     concat6[0][0]                    

conv6_1_bn (BatchNormalization) (None, 8, 8, 256)    1024        conv6_1[0][0]                    

conv6_2 (Conv2D)                (None, 8, 8, 256)    590080      conv6_1_bn[0][0]                 

conv6_2_bn (BatchNormalization) (None, 8, 8, 256)    1024        conv6_2[0][0]                    

conv2d_transpose_2 (Conv2DTrans (None, 16, 16, 128)  131200      conv6_2_bn[0][0]                 

dropout_6 (Dropout)             (None, 16, 16, 128)  0           conv2d_transpose_2[0][0]         

concat7 (Concatenate)           (None, 16, 16, 256)  0           conv3_2_bn[0][0]                 
                                                                 dropout_6[0][0]                  

conv7_1 (Conv2D)                (None, 16, 16, 128)  295040      concat7[0][0]                    

conv7_1_bn (BatchNormalization) (None, 16, 16, 128)  512         conv7_1[0][0]                    

conv7_2 (Conv2D)                (None, 16, 16, 128)  147584      conv7_1_bn[0][0]                 

conv7_2_bn (BatchNormalization) (None, 16, 16, 128)  512         conv7_2[0][0]                    

conv2d_transpose_3 (Conv2DTrans (None, 32, 32, 64)   32832       conv7_2_bn[0][0]                 

dropout_7 (Dropout)             (None, 32, 32, 64)   0           conv2d_transpose_3[0][0]         

concat8 (Concatenate)           (None, 32, 32, 128)  0           conv2_2_bn[0][0]                 
                                                                 dropout_7[0][0]                  

conv8_1 (Conv2D)                (None, 32, 32, 64)   73792       concat8[0][0]                    

conv8_1_bn (BatchNormalization) (None, 32, 32, 64)   256         conv8_1[0][0]                    

conv8_2 (Conv2D)                (None, 32, 32, 64)   36928       conv8_1_bn[0][0]                 

conv8_2_bn (BatchNormalization) (None, 32, 32, 64)   256         conv8_2[0][0]                    

conv2d_transpose_4 (Conv2DTrans (None, 64, 64, 32)   8224        conv8_2_bn[0][0]                 

dropout_8 (Dropout)             (None, 64, 64, 32)   0           conv2d_transpose_4[0][0]         

concat9 (Concatenate)           (None, 64, 64, 64)   0           conv1_2_bn[0][0]                 
                                                                 dropout_8[0][0]                  

conv9_1 (Conv2D)                (None, 64, 64, 32)   18464       concat9[0][0]                    

conv9_1_bn (BatchNormalization) (None, 64, 64, 32)   128         conv9_1[0][0]                    

conv9_2 (Conv2D)                (None, 64, 64, 32)   9248        conv9_1_bn[0][0]                 

conv9_2_bn (BatchNormalization) (None, 64, 64, 32)   128         conv9_2[0][0]                    

dropout_9 (Dropout)             (None, 64, 64, 32)   0           conv9_2_bn[0][0]                 

conv10 (Conv2D)                 (None, 64, 64, 1)    33          dropout_9[0][0]                  


Total params: 7,771,297
Trainable params: 7,765,409
Non-trainable params: 5,888


If you have difficulty to see, please use this link(PDF, google drive).

https://drive.google.com/file/d/1oSXFCd-JI2otik9-z2WstIRmaqwcmpl8/view?usp=sharing

If you need more information, please let me know. 
Thanks.

**Comment by ChoiDM** [comment]
I think you're not using multi-gpu model.
The lambda layer is not added to the network unless the model is on multi-gpu training mode by 'from keras.utils.training_utils import multi_gpu_model'.

So, you can skip 'get_layer' part.
Thanks.

**Comment by Jeonous** [comment]
You are right. I didn't use multi-gpu model.
I tried it but I couldn't do this in the Colab.

I will skip it.
Thanks a lot, Choi.
